server:
  port: 19995

spring:
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://114.115.153.130:3306/?noAccessToProcedureBodies=true&amp;autoReconnect=true&amp;Unicode=true&characterEncoding=utf-8
      username: root
      password: GoodLuck!APP2.0
    slaver:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///?noAccessToProcedureBodies=true&amp;autoReconnect=true&amp;Unicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false
      username: root
      password: root

    druid:
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  thymeleaf:
    cache: false
  application:
    name: statics

mybatis:
  mapper-locations: classpath:mybatis/mapper/master/*.xml
  config-location: classpath:mybatis/config.xml

logging:
  level:
    com.xusage.statics.dao: DEBUG
  file:
    logs/si.log

